- name: Install JRE after apt update
  become: yes
  apt:
    name: 
      - default-jre
    state: present
    update_cache: yes

- name: Create a group 
  become: yes
  group:
    name: "{{username}}"
    state: present

- name: Create an user 
  become: yes
  user:
    name: "{{username}}"
    state: present
    group: kafka

- name: Create a Installation Directory 
  become: yes
  file:
    path: "{{installation_dir}}"
    state: directory
    mode: 0755
    owner: kafka
    group: kafka

- name: Download Kafka and Unzip 
  become: yes
  become_user: kafka
  unarchive:
    src: https://downloads.apache.org/kafka/3.3.1/kafka_2.13-3.3.1.tgz
    dest: "{{installation_dir}}"
    mode: 0755
    remote_src: yes

- name: Move all the files to parent Directory
  become: yes
  become_user: kafka
  shell:
    mv {{installation_dir}}/kafka_*/* {{installation_dir}}/.