- name: Install JRE after apt update
  become: yes
  apt:
    name: 
      - default-jre
    state: present
    update_cache: yes

- name: Create a group 
  become: yes
  group:
    name: "{{username}}"
    state: present

- name: Create an user 
  become: yes
  user:
    name: "{{username}}"
    state: present
    group: kafka

- name: Remove content from install directory
  become: true
  shell: "rm -r {{installation_dir}}/*"

- name: Create a Installation Directory 
  become: yes
  file:
    path: "{{installation_dir}}"
    state: directory
    mode: 0755
    owner: kafka
    group: kafka

- name: Download Kafka and Unzip 
  become: yes
  unarchive:
    src: https://downloads.apache.org/kafka/3.3.1/kafka_2.13-3.3.1.tgz
    dest: "{{installation_dir}}"
    mode: 0755
    remote_src: yes

- name: Update the Java Heap Size for Kafka
  become: yes
  replace:
    path: "{{installation_dir}}/bin/kafka-server-start.sh"
    regexp: 'export KAFKA_HEAP_OPTS=(".+")'
    replace: 'export KAFKA_HEAP_OPTS="-Xmx1024M -Xms1024M"'
    backup: yes

- name: generate id for cluster
  shell: "{{ installation_dir }}/bin/kafka-storage.sh random-uuid"
  register: uuid_output

- name: format storage directory
  shell: "{{ installation_dir }}/bin/kafka-storage.sh format -t {{ uuid_output.stdout }} -c {{ installation_dir }}/config/kraft/server.properties"

- name: launch broker
  shell: "{{ installation_dir }}/bin/kafka-server-start.sh {{ installation_dir }}/config/kraft/server.properties"